
Vagrant.configure("2") do |config|

  config.winrm.timeout =   600 # 30 minutes
  config.vm.boot_timeout = 600 # 30 minutes
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    v.gui = true
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/xenial64"
#    db.vm.box = "generic/ubuntu2004"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"
#    db.vm.network :public_network, bridge: "Intel(R) Dual Band Wireless-AC 7265"
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
#    db.vm.provision "ansible" do |ansible|
#      ansible.playbook = "playbooks/site.yml"
#      ansible.groups = {
#      "db" => ["dbserver"],
#      "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
#      }
#    end
  end
  
  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/xenial64"
#    app.vm.box = "generic/ubuntu2004"
    app.vm.hostname = "appserver"
#    app.vm.network :private_network, ip: "10.10.10.20"
    app.vm.network :public_network
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
  end
end
